permissions:
  shopkeepersstock.*:
    description: 'Grants all ShopkeepersStockControl permissions'
    default: op
    children:
      shopkeepersstock.admin: true

  shopkeepersstock.admin:
    description: 'Admin access to all SSC commands'
    default: op
